### ISSUE TITLE
June 24 - ToDo 

### ISSUE THREAD

**Issue by khan129** [khan129/AK_AutoArm#6]
- [ ] test proof it

- [ ] try to see if you can use pyth to find dir of XYZ for stretch

- [ ] optimize lines

- [ ] separate function and guis so they can work independently.
